# Generated by Django 5.0.1 on 2024-04-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Names", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=10)),
                ("National_ID", models.CharField(max_length=8)),
                ("County", models.CharField(max_length=8)),
            ],
        ),
    ]
